language: php

sudo: required

php:
  - 5.6
  - 7.0
env:
  matrix:
    - PHALCON_VERSION="v3.0.1"
    - PHALCON_VERSION="v3.0.2"
    - PHALCON_VERSION="3.0.x"

install:
  - composer self-update
  - git clone --depth=1 -q --branch=${PHALCON_VERSION} https://github.com/phalcon/cphalcon.git
  - '(cd cphalcon/build; bash install &>/dev/null && phpenv config-add ../tests/_ci/phalcon.ini &> /dev/null && cd ../..;)'
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - travis_retry composer install --no-interaction --prefer-source --dev

before_script:
  - composer dump-autoload

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls