language: php

sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - PHALCON_VERSION="v3.0.4"
  - PHALCON_VERSION="v3.1.2"
  - PHALCON_VERSION="v3.2.4"
  - PHALCON_VERSION="v3.3.2"
  - PHALCON_VERSION="v3.4.5"

matrix:
  exclude:
  - php: 7.1
    env: PHALCON_VERSION="v3.0.4"
  - php: 7.2
    env: PHALCON_VERSION="v3.0.4"
  - php: 7.3
    env: PHALCON_VERSION="v3.0.4"
  - php: 7.3
    env: PHALCON_VERSION="v3.1.2"
  - php: 7.3
    env: PHALCON_VERSION="v3.2.4"
  - php: 7.3
    env: PHALCON_VERSION="v3.3.2"

before_install:
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/phpize /usr/bin/
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/php-config /usr/bin/
  - git clone --depth=1 -q --branch=${PHALCON_VERSION} https://github.com/phalcon/cphalcon.git
  - cd cphalcon/build
  - bash install
  - phpenv config-add ../tests/_ci/phalcon.ini
  - cd ../../

install:
  - php -v
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - php -m
  - travis_retry composer install --no-interaction --prefer-source --dev

before_script:
  - composer dump-autoload

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml --verbose --debug

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls